CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT UNIQUE NOT NULL,
    age INTEGER,
    condition TEXT NOT NULL,
    drug_name TEXT NOT NULL,
    drug_dosage TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'chronic',
    service_type TEXT DEFAULT '',
    care_instructions TEXT DEFAULT '',
    next_follow_up TEXT DEFAULT '',
    recall_date TEXT DEFAULT '',
    reminder_time TEXT NOT NULL DEFAULT '08:00',
    enrolled_at TEXT NOT NULL,
    doctor_name TEXT DEFAULT 'Dr. Mensah',
    status TEXT DEFAULT 'active',
    risk_level TEXT DEFAULT 'green',
    preferred_language TEXT NOT NULL DEFAULT 'en',
    consent_status TEXT NOT NULL DEFAULT 'pending',
    consent_recorded_at TEXT,
    consent_recorded_by TEXT DEFAULT '',
    communication_opt_in INTEGER NOT NULL DEFAULT 0,
    paused INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS staff_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('admin', 'care_team')),
    password_hash TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TEXT,
    last_login_at TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    direction TEXT NOT NULL,
    body TEXT NOT NULL,
    reason TEXT,
    created_at TEXT NOT NULL,
    channel TEXT DEFAULT 'simulator',
    audio_file TEXT DEFAULT '',
    stt_provider TEXT DEFAULT '',
    stt_language TEXT DEFAULT '',
    stt_latency_ms INTEGER DEFAULT 0,
    tts_provider TEXT DEFAULT '',
    tts_voice TEXT DEFAULT '',
    tts_latency_ms INTEGER DEFAULT 0,
    spoken_body TEXT DEFAULT '',
    delivery_status TEXT DEFAULT '',
    delivery_error TEXT DEFAULT '',
    external_message_id TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS adherence_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    log_date TEXT NOT NULL,
    response TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS checkin_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    reading_type TEXT NOT NULL,
    reading_value TEXT NOT NULL,
    risk_level TEXT NOT NULL,
    ai_note TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation_state (
    patient_id BIGINT PRIMARY KEY REFERENCES patients(id),
    current_flow TEXT DEFAULT 'idle',
    context TEXT DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS escalations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    reason TEXT NOT NULL,
    risk_level TEXT NOT NULL,
    details TEXT NOT NULL,
    resolved INTEGER DEFAULT 0,
    resolution_code TEXT DEFAULT '',
    resolution_note TEXT DEFAULT '',
    resolved_by TEXT DEFAULT '',
    resolved_at TEXT,
    assigned_to BIGINT REFERENCES staff_users(id),
    acknowledged_at TEXT,
    acknowledged_by BIGINT REFERENCES staff_users(id),
    due_at TEXT,
    notification_status TEXT DEFAULT '',
    notification_error TEXT DEFAULT '',
    notification_message_id TEXT DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS staff_sessions (
    token_hash TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES staff_users(id) ON DELETE CASCADE,
    csrf_token TEXT NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    user_agent TEXT DEFAULT '',
    ip_address TEXT DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_staff_sessions_expiry ON staff_sessions(expires_at);

CREATE TABLE IF NOT EXISTS inbound_events (
    external_message_id TEXT PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'processing',
    received_at TEXT NOT NULL,
    processed_at TEXT,
    error TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS reminder_dispatches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    reminder_kind TEXT NOT NULL,
    dispatch_date TEXT NOT NULL,
    scheduled_for TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT DEFAULT '',
    external_message_id TEXT DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(patient_id, reminder_kind, dispatch_date)
);

CREATE TABLE IF NOT EXISTS consent_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    consent_status TEXT NOT NULL,
    method TEXT NOT NULL,
    recorded_by TEXT NOT NULL,
    note TEXT DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_consent_events_patient ON consent_events(patient_id, created_at);

CREATE TABLE IF NOT EXISTS clinic_settings (
    id INTEGER PRIMARY KEY CHECK(id=1),
    clinic_name TEXT NOT NULL DEFAULT 'VeloxaCare Clinic',
    timezone TEXT NOT NULL DEFAULT 'Africa/Accra',
    escalation_phone TEXT DEFAULT '',
    updated_at TEXT NOT NULL,
    updated_by BIGINT REFERENCES staff_users(id)
);

CREATE TABLE IF NOT EXISTS audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_user_id BIGINT REFERENCES staff_users(id),
    staff_name TEXT NOT NULL,
    action TEXT NOT NULL,
    subject_type TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    details TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_events_created ON audit_events(created_at);

CREATE TABLE IF NOT EXISTS care_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    log_date TEXT NOT NULL,
    activity TEXT NOT NULL,
    response TEXT NOT NULL,
    details TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id),
    appointment_date TEXT NOT NULL,
    appointment_time TEXT NOT NULL,
    clinician_name TEXT NOT NULL,
    visit_type TEXT NOT NULL DEFAULT 'Clinic consultation',
    status TEXT NOT NULL DEFAULT 'confirmed',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_appointments_confirmed_slot
ON appointments(clinician_name, appointment_date, appointment_time)
WHERE status='confirmed';

CREATE INDEX IF NOT EXISTS idx_appointments_patient_date
ON appointments(patient_id, appointment_date, appointment_time);

CREATE INDEX IF NOT EXISTS idx_messages_patient_created
ON messages(patient_id, created_at);

CREATE INDEX IF NOT EXISTS idx_escalations_open_due
ON escalations(resolved, due_at);

ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE adherence_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkin_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE escalations ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE inbound_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminder_dispatches ENABLE ROW LEVEL SECURITY;
ALTER TABLE consent_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinic_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE care_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE schema_migrations ENABLE ROW LEVEL SECURITY;
